language: elixir
elixir:
  - 1.8
env:
  - MIX_ENV=test
before_install:
  - curl https://dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-386.tar.gz --output go-ipfs.tar.gz
  - tar xvfz go-ipfs.tar.gz
  - cd go-ipfs
  - sudo ./install.sh
  - cd ..
  - ipfs init
script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
  - mix all_tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
