name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Install Go IPFS
      run: |
        curl https://dist.ipfs.tech/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-386.tar.gz --output go-ipfs.tar.gz
        # curl https://dist.ipfs.tech/go-ipfs/v0.29.0/go-ipfs_v0.29.0_linux-386.tar.gz --output go-ipfs.tar.gz
        tar xvfz go-ipfs.tar.gz
        cd go-ipfs
        sudo ./install.sh
        cd ..
        ipfs init

    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.2' # Define the elixir version [required]
        otp-version: '25.1.2' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix coveralls.json
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
